ciudades = [
    ['Juan', 'Jorge', 'Sofia', 'Jorge', 'Isabella', 'Martina', 'Maria', 'Sofia', 'Nicolás', 'Martina', 'Juan', 'Camila', 'Santiago', 'Martina', 'Isabella', 'Camila', 'Jorge', 'Isabella', 'Daniela', 'Juan', 'Manuel', 'Daniela', 'Valentina', 'Manuel', 'Maria', 'Gabriel', 'Victoria', 'Alejandro', 'Camila', 'Diego', 'Victoria', 'Jorge', 'Daniela', 'Carlos', 'Diego', 'Sofia', 'Mateo', 'Diego', 'Carlos', 'Maria', 'Isabella', 'Gabriel', 'Gabriel', 'Gabriel', 'Juan', 'Sofia', 'Camila', 'Gabriel', 'Jorge', 'Santiago', 'Jorge', 'Camila', 'Lucia', 'Jorge', 'Isabella', 'Paula', 'Jorge', 'Camila', 'Juan', 'Daniela', 'Martina', 'Jorge', 'Gabriel', 'Camila', 'Nicolás', 'Martina', 'Camila', 'Isabella', 'Camila', 'Mateo', 'Lucas', 'Isabella', 'Camila', 'Isabella', 'Daniela', 'Jorge', 'Elena', 'Camila', 'Alejandro', 'Martina', 'Victoria', 'Mateo', 'Jorge', 'Isabella', 'Elena', 'Isabella', 'Jorge', 'Carlos', 'Manuel', 'Camila', 'Alejandro', 'Jorge', 'Daniela', 'Diego', 'Jorge', 'Juan', 'Daniela', 'Gabriel', 'Valentina', 'Jorge'],
    ['Mateo', 'Elena', 'Santiago', 'Camila', 'Camila', 'Victoria', 'Mateo', 'Isabella', 'Lucia', 'Maria', 'Jorge', 'Diego', 'Santiago', 'Camila', 'Martina', 'Nicolás', 'Camila', 'Victoria', 'Martina', 'Santiago', 'Lucia', 'Camila', 'Juan', 'Lucas', 'Sofia', 'Jorge', 'Jorge', 'Diego', 'Juan', 'Maria', 'Camila', 'Camila', 'Camila', 'Victoria', 'Juan', 'Jorge', 'Camila', 'Juan', 'Victoria', 'Nicolás', 'Carlos', 'Santiago', 'Manuel', 'Camila', 'Camila', 'Sofia', 'Camila', 'Manuel', 'Mateo', 'Victoria', 'Mateo', 'Elena', 'Jorge', 'Jorge', 'Carlos', 'Nicolás', 'Victoria', 'Santiago', 'Camila', 'Manuel', 'Daniela', 'Nicolás', 'Victoria', 'Isabella', 'Lucas', 'Camila', 'Juan', 'Camila', 'Juan', 'Valentina', 'Elena', 'Martina', 'Mateo', 'Maria', 'Daniela', 'Santiago', 'Manuel', 'Juan', 'Jorge', 'Jorge', 'Camila', 'Carlos', 'Gabriel', 'Mateo', 'Lucas', 'Juan', 'Maria', 'Elena', 'Victoria', 'Camila', 'Nicolás', 'Manuel', 'Jorge', 'Sofia', 'Carlos', 'Martina', 'Paula', 'Camila', 'Jorge', 'Jorge'],
    ['Camila', 'Camila', 'Isabella', 'Carlos', 'Alejandro', 'Lucas', 'Santiago', 'Valentina', 'Jorge', 'Jorge', 'Camila', 'Sofia', 'Jorge', 'Nicolás', 'Maria', 'Nicolás', 'Jorge', 'Camila', 'Manuel', 'Daniela', 'Maria', 'Maria', 'Valentina', 'Carlos', 'Jorge', 'Camila', 'Nicolás', 'Mateo', 'Sofia', 'Diego', 'Jorge', 'Victoria', 'Paula', 'Alejandro', 'Jorge', 'Lucas', 'Daniela', 'Lucia', 'Camila', 'Paula', 'Daniela', 'Camila', 'Manuel', 'Camila', 'Jorge', 'Sofia', 'Camila', 'Jorge', 'Jorge', 'Victoria', 'Victoria', 'Daniela', 'Mateo', 'Martina', 'Juan', 'Jorge', 'Elena', 'Juan', 'Sofia', 'Lucia', 'Carlos', 'Lucia', 'Diego', 'Alejandro', 'Camila', 'Manuel', 'Martina', 'Jorge', 'Santiago', 'Elena', 'Daniela', 'Isabella', 'Camila', 'Martina', 'Alejandro', 'Camila', 'Victoria', 'Paula', 'Elena', 'Camila', 'Jorge', 'Alejandro', 'Camila', 'Lucia', 'Paula', 'Daniela', 'Isabella', 'Nicolás', 'Isabella', 'Juan', 'Santiago', 'Manuel', 'Jorge', 'Lucia', 'Jorge', 'Victoria', 'Mateo', 'Victoria', 'Gabriel', 'Paula'],
    ['Camila', 'Jorge', 'Juan', 'Camila', 'Nicolás', 'Gabriel', 'Juan', 'Camila', 'Mateo', 'Jorge', 'Mateo', 'Camila', 'Victoria', 'Camila', 'Alejandro', 'Victoria', 'Maria', 'Jorge', 'Alejandro', 'Alejandro', 'Sofia', 'Camila', 'Valentina', 'Jorge', 'Diego', 'Santiago', 'Isabella', 'Camila', 'Jorge', 'Elena', 'Jorge', 'Nicolás', 'Victoria', 'Manuel', 'Lucia', 'Paula', 'Jorge', 'Paula', 'Juan', 'Santiago', 'Victoria', 'Manuel', 'Jorge', 'Jorge', 'Juan', 'Jorge', 'Camila', 'Elena', 'Diego', 'Nicolás', 'Jorge', 'Camila', 'Camila', 'Jorge', 'Juan', 'Martina', 'Maria', 'Camila', 'Valentina', 'Elena', 'Maria', 'Daniela', 'Jorge', 'Paula', 'Camila', 'Camila', 'Camila', 'Lucas', 'Jorge', 'Manuel', 'Camila', 'Victoria', 'Camila', 'Nicolás', 'Camila', 'Sofia', 'Camila', 'Camila', 'Valentina', 'Jorge', 'Elena', 'Elena', 'Juan', 'Camila', 'Mateo', 'Victoria', 'Manuel', 'Martina', 'Jorge', 'Alejandro', 'Paula', 'Alejandro', 'Camila', 'Maria', 'Mateo', 'Isabella', 'Carlos', 'Camila', 'Isabella', 'Jorge'],
    ['Sofia', 'Alejandro', 'Jorge', 'Nicolás', 'Jorge', 'Carlos', 'Santiago', 'Jorge', 'Gabriel', 'Jorge', 'Daniela', 'Maria', 'Jorge', 'Victoria', 'Jorge', 'Mateo', 'Santiago', 'Lucas', 'Camila', 'Lucas', 'Manuel', 'Manuel', 'Camila', 'Jorge', 'Jorge', 'Juan', 'Diego', 'Victoria', 'Santiago', 'Jorge', 'Sofia', 'Daniela', 'Diego', 'Juan', 'Lucia', 'Camila', 'Paula', 'Alejandro', 'Manuel', 'Valentina', 'Gabriel', 'Manuel', 'Paula', 'Jorge', 'Camila', 'Sofia', 'Camila', 'Santiago', 'Manuel', 'Camila', 'Jorge', 'Jorge', 'Jorge', 'Martina', 'Diego', 'Jorge', 'Nicolás', 'Victoria', 'Camila', 'Mateo', 'Santiago', 'Sofia', 'Camila', 'Valentina', 'Camila', 'Valentina', 'Lucas', 'Jorge', 'Gabriel', 'Santiago', 'Alejandro', 'Paula', 'Diego', 'Paula', 'Lucia', 'Valentina', 'Camila', 'Victoria', 'Gabriel', 'Elena', 'Santiago', 'Camila', 'Santiago', 'Carlos', 'Jorge', 'Lucas', 'Camila', 'Maria', 'Jorge', 'Juan', 'Jorge', 'Juan', 'Camila', 'Camila', 'Camila', 'Sofia', 'Daniela', 'Camila', 'Daniela', 'Carlos'],
    ['Carlos', 'Lucas', 'Gabriel', 'Paula', 'Jorge', 'Manuel', 'Gabriel', 'Lucas', 'Nicolás', 'Isabella', 'Jorge', 'Jorge', 'Camila', 'Nicolás', 'Mateo', 'Sofia', 'Juan', 'Maria', 'Camila', 'Victoria', 'Jorge', 'Lucia', 'Lucia', 'Nicolás', 'Juan', 'Manuel', 'Valentina', 'Jorge', 'Lucia', 'Santiago', 'Elena', 'Sofia', 'Daniela', 'Isabella', 'Camila', 'Jorge', 'Camila', 'Jorge', 'Alejandro', 'Camila', 'Camila', 'Camila', 'Maria', 'Alejandro', 'Carlos', 'Maria', 'Jorge', 'Victoria', 'Alejandro', 'Jorge', 'Isabella', 'Juan', 'Jorge', 'Mateo', 'Diego', 'Daniela', 'Jorge', 'Paula', 'Lucia', 'Camila', 'Lucia', 'Carlos', 'Isabella', 'Jorge', 'Santiago', 'Camila', 'Lucas', 'Camila', 'Valentina', 'Camila', 'Maria', 'Camila', 'Maria', 'Lucia', 'Sofia', 'Mateo', 'Lucas', 'Jorge', 'Valentina', 'Camila', 'Jorge', 'Alejandro', 'Martina', 'Juan', 'Nicolás', 'Santiago', 'Paula', 'Camila', 'Mateo', 'Sofia', 'Martina', 'Paula', 'Paula', 'Isabella', 'Gabriel', 'Jorge', 'Elena', 'Sofia', 'Manuel', 'Nicolás'],
    ['Santiago', 'Mateo', 'Daniela', 'Isabella', 'Camila', 'Camila', 'Camila', 'Carlos', 'Lucas', 'Daniela', 'Jorge', 'Jorge', 'Maria', 'Carlos', 'Jorge', 'Diego', 'Lucia', 'Jorge', 'Jorge', 'Jorge', 'Carlos', 'Camila', 'Lucas', 'Jorge', 'Daniela', 'Alejandro', 'Camila', 'Daniela', 'Gabriel', 'Sofia', 'Isabella', 'Nicolás', 'Jorge', 'Santiago', 'Maria', 'Lucas', 'Camila', 'Paula', 'Alejandro', 'Martina', 'Camila', 'Alejandro', 'Maria', 'Jorge', 'Jorge', 'Daniela', 'Camila', 'Manuel', 'Camila', 'Jorge', 'Nicolás', 'Paula', 'Camila', 'Santiago', 'Jorge', 'Jorge', 'Camila', 'Camila', 'Gabriel', 'Jorge', 'Juan', 'Jorge', 'Jorge', 'Diego', 'Elena', 'Diego', 'Maria', 'Juan', 'Maria', 'Victoria', 'Daniela', 'Jorge', 'Jorge', 'Camila', 'Daniela', 'Camila', 'Mateo', 'Santiago', 'Elena', 'Manuel', 'Jorge', 'Carlos', 'Lucas', 'Nicolás', 'Manuel', 'Alejandro', 'Santiago', 'Camila', 'Maria', 'Martina', 'Paula', 'Camila', 'Valentina', 'Nicolás', 'Alejandro', 'Victoria', 'Daniela', 'Maria', 'Valentina', 'Manuel'],
    ['Santiago', 'Camila', 'Nicolás', 'Sofia', 'Victoria', 'Jorge', 'Paula', 'Isabella', 'Isabella', 'Paula', 'Jorge', 'Lucia', 'Camila', 'Camila', 'Carlos', 'Carlos', 'Maria', 'Martina', 'Santiago', 'Alejandro', 'Camila', 'Jorge', 'Camila', 'Diego', 'Paula', 'Juan', 'Carlos', 'Victoria', 'Sofia', 'Elena', 'Lucas', 'Manuel', 'Martina', 'Mateo', 'Lucia', 'Mateo', 'Lucia', 'Nicolás', 'Mateo', 'Nicolás', 'Jorge', 'Santiago', 'Camila', 'Martina', 'Camila', 'Gabriel', 'Martina', 'Alejandro', 'Santiago', 'Carlos', 'Jorge', 'Isabella', 'Jorge', 'Paula', 'Alejandro', 'Carlos', 'Jorge', 'Nicolás', 'Nicolás', 'Gabriel', 'Mateo', 'Jorge', 'Gabriel', 'Victoria', 'Juan', 'Martina', 'Alejandro', 'Martina', 'Camila', 'Gabriel', 'Juan', 'Jorge', 'Jorge', 'Carlos', 'Camila', 'Mateo', 'Nicolás', 'Jorge', 'Mateo', 'Manuel', 'Jorge', 'Martina', 'Alejandro', 'Martina', 'Jorge', 'Paula', 'Diego', 'Diego', 'Manuel', 'Victoria', 'Maria', 'Jorge', 'Mateo', 'Paula', 'Nicolás', 'Manuel', 'Nicolás', 'Daniela', 'Sofia', 'Manuel'],
    ['Jorge', 'Juan', 'Camila', 'Diego', 'Carlos', 'Jorge', 'Nicolás', 'Jorge', 'Mateo', 'Jorge', 'Victoria', 'Manuel', 'Isabella', 'Jorge', 'Sofia', 'Lucas', 'Elena', 'Isabella', 'Camila', 'Paula', 'Jorge', 'Martina', 'Elena', 'Manuel', 'Juan', 'Gabriel', 'Lucas', 'Juan', 'Camila', 'Martina', 'Martina', 'Gabriel', 'Carlos', 'Manuel', 'Paula', 'Camila', 'Juan', 'Jorge', 'Mateo', 'Valentina', 'Maria', 'Jorge', 'Jorge', 'Victoria', 'Camila', 'Diego', 'Camila', 'Manuel', 'Daniela', 'Lucas', 'Jorge', 'Alejandro', 'Jorge', 'Camila', 'Daniela', 'Isabella', 'Jorge', 'Paula', 'Victoria', 'Nicolás', 'Camila', 'Camila', 'Camila', 'Jorge', 'Isabella', 'Carlos', 'Maria', 'Jorge', 'Paula', 'Jorge', 'Santiago', 'Daniela', 'Daniela', 'Camila', 'Mateo', 'Sofia', 'Jorge', 'Lucia', 'Gabriel', 'Paula', 'Juan', 'Mateo', 'Jorge', 'Camila', 'Maria', 'Lucas', 'Elena', 'Victoria', 'Maria', 'Jorge', 'Elena', 'Daniela', 'Carlos', 'Nicolás', 'Carlos', 'Mateo', 'Camila', 'Alejandro', 'Paula', 'Jorge'],
]

buscado = 0
total = 0
persona=input("A quien vas a buscar?")
for barrio in ciudades:
    for nombre in barrio:
        if nombre == persona:
            buscado = buscado+1
            total = total+1
    print(f" En el barrio {ciudades.index(barrio)+1} hay {buscado} {persona}")
    buscado = 0
print(f"En total hay {total} {persona}")